
SET IDENTITY_INSERT [dbo].[Proverbs] ON
INSERT INTO [dbo].[Proverbs] ([Author], [Saying], [Id], [Language]) 
VALUES (N'Proverbe Espagnol', N'Offrir l''amitié à qui veut l''amour, c''est donner du pain à qui meurt de soif.', 1, N'Français'),
		(N'Proverbe Africain', N'Le bonheur ne s''acquiert pas, il ne réside pas dans les apparences, chacun d''entre nous le construit à chaque instant de sa vie avec son coeur.', 2, N'Français'),
		(N'Proverbe Français', N'Quand la pauvreté entre par la porte, l''amour s''en va par la fenêtre.', 3, N'Français'),
		(N'Proverbe Algérien', N'Parmi les hommes, le plus faible est celui qui ne sait pas garder un secret. Le plus fort, celui qui maîtrise sa colère, le plus patient, celui qui cache sa pauvreté, le plus riche, celui qui se contente de la part que dieu lui a faite.', 4, N'Français'),
		(N'Proverbe Arabe', N'Souviens-toi qu''au moment de ta naissance tout le monde était dans la joie et toi dans les pleurs. Vis de manière qu''au moment de ta mort, tout le monde soit dans les pleurs et toi dans la joie.', 5, N'Français'),
		(N'Proverbe Chinois', N'Il vaut mieux se disputer avec quelqu''un d''intelligent que parler à un imbécile.', 6, N'Français'),
		(N'Proverbe Africain', N'La femme est la ceinture qui tient le pantalon de l''homme.', 7, N'Français'),
		(N'Proverbe Français', N'On ne peut empêcher le chien d''aboyer, ni le menteur de mentir.', 8, N'Français'),
		(N'Proverbe Italien', N'Mieux vaut vivre un jour comme un lion que cent ans comme un mouton.', 9, N'Français'),
		(N'Proverbe Arabe', N'Qui veut faire quelque chose trouve un moyen, qui ne veut rien faire trouve une excuse.', 10, N'Français'),
		(N'Proverbe Français', N'L''amitié se finit parfois en amour, mais rarement l''amour en amitié.', 11, N'Français'),
		(N'Proverbe Français', N'La douceur du miel ne console pas de la piqûre de l''abeille.', 12, N'Français'),
		(N'Proverbe Français', N'Avec du temps et de la patience, on vient à bout de tout.', 13, N'Français'),
		(N'Proverbe Africain', N'On ne peut pas peindre du blanc sur du blanc, du noir sur du noir. Chacun a besoin de l''autre pour se révéler.', 14, N'Français'),
		(N'Proverbe Chinois', N'Quand on achète une maison, on regarde les poutres ; quand on prend une femme, il faut regarder la mère.', 15, N'Français'),
		(N'Proverbe Africain', N'Le mensonge donne des fleurs mais pas de fruits.', 16, N'Français'),
		(N'Proverbe Français', N'Un bon père de famille doit être partout, Dernier couché premier debout.', 17, N'Français'),
		(N'Proverbe Africain', N'Le silence est la seule chose en or que les femmes n''aiment pas.', 18, N'Français'),
		(N'Proverbe Arabe', N'Ne dis pas tes peines à autrui ; l''épervier et le vautour s''abattent sur le blessé qui gémit.', 19, N'Français'),
		(N'Proverbe Français', N'Vieille amitié ne craint pas la rouille.', 20, N'Français'),
		(N'Proverbe Arabe', N'Lorsque Dieu ferme une porte, il en ouvre toujours une autre.', 21, N'Français'),
		(N'Proverbe Africain', N'Si vous voulez savoir la vérité, écoutez les fous.', 22, N'Français'),
		(N'Proverbe Africain', N'L''argent est bien, mais l''homme est meilleur, parce qu''il répond quand on l''appelle.', 23, N'Français'),
		(N'Proverbe Français', N'Plus on désire une chose, plus elle se fait attendre.', 24, N'Français'),
		(N'Proverbe Africain', N'Lorsque tu ne sais pas où tu vas, regarde d''où tu viens.', 25, N'Français'),
		(N'Proverbe Africain', N'Quand un arbre tombe, on l''entend ; quand la forêt pousse, pas un bruit.', 26, N'Français'),
		(N'Proverbe Francais', N'Celui qui sème l''injustice moissonne le malheur.', 27, N'Français'),
		(N'Proverbe Italien', N'Si vous enseignez à un homme, vous enseignez à une personne. Si vous enseignez à une femme, vous enseignez à toute la famille.', 28, N'Français'),
		(N'Proverbe Chinois', N'Mieux vaut mille refus qu''une promesse non tenue.', 29, N'Français'),
		(N'Proverbe Africain', N'Si tu veux aller vite, marche seul mais si tu veux aller loin, marchons ensemble.', 30, N'Français'),
		(N'Proverbe Chinois', N'Quand on suit quelqu''un de bon, on apprend à devenir bon ; quand on suit un tigre, on apprend à mordre.', 31, N'Français'),
		(N'Proverbe Chinois', N'J''étais furieux de n''avoir pas de souliers ; alors j''ai rencontré un homme qui n''avait pas de pieds, et je me suis trouvé content de mon sort.', 32, N'Francais'),
		(N'Proverbe Persan', N'La patience est un arbre dont la racine est amère, et dont les fruits sont très doux.', 33, N'Français'),
		(N'Proverbe Italien', N'Qui te craint en ta présence, te nuit en ton absence.', 34, N'Français'),
		(N'Proverbe Arabe', N'N''ouvre la bouche que si tu es sûr que ce que tu vas dire est plus beau que le silence.', 35, N'Français'),
		(N'Proverbe Chinois', N'Paix et tranquillité, voilà le bonheur.', 36, N'Français'),
		(N'Proverbe Japonais', N'On apprend peu par la victoire, mais beaucoup par la défaite.', 37, N'Français'),
		(N'Proverbe Français', N'Quand Dieu donne le mal, il donne aussi le remède.', 38, N'Français'),
		(N'Proverbe Chinois', N'Les grandes âmes ont de la volonté, les faibles n''ont que des souhaits.', 39, N'Français'),
		(N'Proverbe Arabe', N'Dans la nuit noire, sur la pierre noire, une fourmi noire. Dieu la voit.', 40, N'Français'),
		(N'Proverbe Arabe', N'Le chameau ne voit pas sa propre bosse, il voit la bosse de son frère.', 41, N'Français'),
		(N'Proverbe Chinois', N'Un bon chef de famille, c''est celui qui se montre un peu sourd.', 42, N'Français'),
		(N'Proverbe Algérien', N'L''amour et la haine sont un voile devant les yeux : l''une ne laisse voir que le bien, l''autre que le mal.', 43, N'Français'),
		(N'Proverbe Chinois', N'Point n''est besoin d''élever la voix quand on a raison.', 44, N'Français'),
		(N'Proverbe Français', N'On attrape plus vite un menteur qu''un voleur.', 45, N'Français'),
		(N'Proverbe Africain', N'La délicatesse des gestes révèle celle des sentiments.', 46, N'Français'),
		(N'Proverbe Turc', N'La nature, qui ne nous a donné qu''un seul organe pour la parole, nous en a donné deux pour l''ouïe, afin de nous apprendre qu''il faut plus écouter que parler.', 47, N'Français'),
		(N'Proverbe Arabe', N'C''est de la confiance que naît la trahison.', 48, N'Français'),
		(N'Proverbe Japonnais', N'L''amour d''un père est plus haut que la montagne. L''amour d''une mère est plus profond que l''océan.', 49, N'Français'),
		(N'Proverbe Chinois', N'Ce n''est qu''avec les yeux des autres que l''on peut bien voir ses défauts.', 50, N'Français')

SET IDENTITY_INSERT [dbo].[Proverbs] OFF